#!/bin/bash
DEPLOY_SOURCE=$(dirname $(dirname $0))
[ -z "$DEPLOY_TIMESTAMP" ] && DEPLOY_TIMESTAMP=$(date +"%Y%m%d%H%M%S")
[ -z "$DEPLOY_USER" ] && DEPLOY_USER=ubuntu
[ -z "$DEPLOY_SERVER" ] && DEPLOY_SERVER=example.com
[ -z "$DEPLOY_ROOT" ] && DEPLOY_ROOT=/var/sites/example.com
[ -z "$DEPLOY_PATH" ] && DEPLOY_PATH=${DEPLOY_ROOT}/revisions/${DEPLOY_TIMESTAMP}
DEPLOY_IDENTITY_FILE=$(realpath ~/.ssh/deploykey.pem)

LINE_COLOR=`echo -en '\e[32m'`
LINE_COLOR_RESET=`echo -en '\e[00m'`

echo "* Deploying to ${DEPLOY_SERVER}"
echo "> rsync -a -e 'ssh -i ${DEPLOY_IDENTITY_FILE}' --exclude=config.local.inc.php ${DEPLOY_SOURCE} ${DEPLOY_USER}@${DEPLOY_SERVER}:${DEPLOY_PATH}${LINE_COLOR}"
rsync -a -e "ssh -i ${DEPLOY_IDENTITY_FILE}" --exclude=config.local.inc.php ${DEPLOY_SOURCE} ${DEPLOY_USER}@${DEPLOY_SERVER}:${DEPLOY_PATH}
echo "${LINE_COLOR_RESET}> ssh -i ${DEPLOY_IDENTITY_FILE} ${DEPLOY_USER}@${DEPLOY_SERVER} 'export DEPLOY_ROOT=${DEPLOY_ROOT} && ${DEPLOY_PATH}/scripts/install'${LINE_COLOR}"
ssh -i ${DEPLOY_IDENTITY_FILE} ${DEPLOY_USER}@${DEPLOY_SERVER} "export DEPLOY_ROOT=${DEPLOY_ROOT} && ${DEPLOY_PATH}/scripts/install"
echo "${LINE_COLOR_RESET}* Done"
