#!/bin/bash
SOURCE=$(dirname $(dirname $0))
[ -z "$TIMESTAMP" ] && TIMESTAMP=$(date +"%Y%m%d%H%M%S")
[ -z "$USER" ] && USER=ubuntu
[ -z "$SERVER" ] && SERVER=example.com
[ -z "$DEPLOY_ROOT" ] && DEPLOY_ROOT=/var/sites/example.com
[ -z "$DEPLOY_PATH" ] && DEPLOY_PATH=${DEPLOY_ROOT}/revisions/${TIMESTAMP}
IDENTITY_FILE=$(realpath ~/.ssh/deploykey.pem)

LINE_COLOR=`echo -en '\e[32m'`
LINE_COLOR_RESET=`echo -en '\e[00m'`

echo "* Deploying to ${SERVER}"
echo "> rsync -a -e 'ssh -i ${IDENTITY_FILE}' --exclude=config.local.inc.php ${SOURCE} ${USER}@${SERVER}:${DEPLOY_PATH}${LINE_COLOR}"
rsync -a -e "ssh -i ${IDENTITY_FILE}" --exclude=config.local.inc.php ${SOURCE} ${USER}@${SERVER}:${DEPLOY_PATH}
echo "${LINE_COLOR_RESET}> ssh -i ${IDENTITY_FILE} ${USER}@${SERVER} 'export DEPLOY_ROOT=${DEPLOY_ROOT} && ${DEPLOY_PATH}/scripts/install'${LINE_COLOR}"
ssh -i ${IDENTITY_FILE} ${USER}@${SERVER} "export DEPLOY_ROOT=${DEPLOY_ROOT} && ${DEPLOY_PATH}/scripts/install"
echo "${LINE_COLOR_RESET}* Done"
