#!/usr/bin/env php
<?php
require_once(dirname(__FILE__) . '/../bootstrap.inc.php');
require_once 'migrations.inc.php';

$migrations_dirs = array($GLOBALS['APPLICATION_ROOT'].'/migrations');
$m = new Migrations(db(), $migrations_dirs);
$m->setup();
foreach ($m->getOutstanding() as $version) {
  $m->migrateVersion($version);
}
echo "Database up to date.\n";